openapi: 3.0.0
info:
  title: Loan Management API
  description: API for managing loan applications
  version: 1.0.0
servers:
  - url: http://localhost:3000/api
    description: Local development server

paths:
  /loans:
    get:
      summary: Get all loans
      description: Retrieve a list of all loan applications
      responses:
        "200":
          description: Successful response with a list of loans
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Loan"
    post:
      summary: Create a new loan
      description: Submit a loan application
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewLoan"
      responses:
        "201":
          description: Loan created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Loan"

  /loans/{id}:
    get:
      summary: Get a loan by ID
      description: Retrieve details of a specific loan
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Loan found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Loan"
        "404":
          description: Loan not found

    patch:
      summary: Update loan status
      description: Modify the status of an existing loan
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  enum: ["PENDING", "APPROVED", "REJECTED"]
      responses:
        "200":
          description: Loan status updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Loan"
        "404":
          description: Loan not found

    delete:
      summary: Delete a loan
      description: Remove a loan from the database
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Loan deleted successfully
        "404":
          description: Loan not found

components:
  schemas:
    Loan:
      type: object
      properties:
        id:
          type: integer
          example: 1
        applicantName:
          type: string
          example: "Alice"
        requestedAmount:
          type: number
          example: 2000
        status:
          type: string
          enum: ["PENDING", "APPROVED", "REJECTED"]
          example: "PENDING"
        createdAt:
          type: string
          format: date-time
          example: "2024-02-21T12:00:00Z"

    NewLoan:
      type: object
      required:
        - applicantName
        - requestedAmount
        - status
      properties:
        applicantName:
          type: string
          example: "Alice"
        requestedAmount:
          type: number
          example: 2000
        status:
          type: string
          enum: ["PENDING", "APPROVED", "REJECTED"]
          example: "PENDING"
